// AUTO-GENERATED by logos-cpp-generator -- do not edit
//
// Bodies for `logos_events:` methods declared in agent_module_plugin_export.h.
// Each call marshals typed args into a QVariantList and routes
// them through LogosModuleContext::emitEventImpl_, which the
// generated provider wires to LogosProviderBase::emitEvent.
#include "agent_module_plugin_export.h"
#include <QString>
#include <QByteArray>
#include <QStringList>
#include <QVariant>
#include <QVariantList>
#include <cstdint>
#include <string>
#include <vector>

void AgentModuleExport::moduleStarted(bool success, const std::string& message, int64_t timestamp) {
    QVariantList _args{QVariant(success), QVariant(QString::fromStdString(message)), QVariant(static_cast<qlonglong>(timestamp))};
    this->emitEventImpl_("moduleStarted", &_args);
}

void AgentModuleExport::moduleStopped(bool success, const std::string& message, int64_t timestamp) {
    QVariantList _args{QVariant(success), QVariant(QString::fromStdString(message)), QVariant(static_cast<qlonglong>(timestamp))};
    this->emitEventImpl_("moduleStopped", &_args);
}

void AgentModuleExport::ownerApprovalRequested(const std::string& requestJson, int64_t attempt, int64_t timestamp) {
    QVariantList _args{QVariant(QString::fromStdString(requestJson)), QVariant(static_cast<qlonglong>(attempt)), QVariant(static_cast<qlonglong>(timestamp))};
    this->emitEventImpl_("ownerApprovalRequested", &_args);
}

