// AUTO-GENERATED by logos-cpp-generator -- do not edit
#pragma once

#include <QObject>
#include <QString>
#include <QVariant>
#include <QStringList>
#include <QVariantList>
#include <QVariantMap>
#include <QByteArray>
#include <QJsonArray>
#include <string>
#include <vector>
#include <cstdint>
#include <functional>

#include "logos_provider_object.h"
#include "interface.h"
#include "logos_types.h"
#include "logos_api.h"
#include "logos_module_context.h"
#include "logos_sdk.h"
#include <memory>
#include <type_traits>

#include "agent_module_plugin_export.h"

#include <nlohmann/json.hpp>

namespace {
inline QVariant nlohmannToQVariant(const nlohmann::json& j) {
    if (j.is_null())    return QVariant();
    if (j.is_boolean()) return QVariant(j.get<bool>());
    if (j.is_number_integer()) return QVariant(static_cast<qlonglong>(j.get<int64_t>()));
    if (j.is_number_unsigned()) return QVariant(static_cast<qulonglong>(j.get<uint64_t>()));
    if (j.is_number_float()) return QVariant(j.get<double>());
    if (j.is_string()) return QVariant(QString::fromStdString(j.get<std::string>()));
    if (j.is_array()) {
        QVariantList list;
        list.reserve(static_cast<int>(j.size()));
        for (const auto& elem : j)
            list.append(nlohmannToQVariant(elem));
        return QVariant(list);
    }
    if (j.is_object()) {
        QVariantMap map;
        for (auto it = j.begin(); it != j.end(); ++it)
            map.insert(QString::fromStdString(it.key()), nlohmannToQVariant(it.value()));
        return QVariant(map);
    }
    return QVariant();
}

#include "logos_result.h"
inline LogosResult stdResultToQt(const StdLogosResult& r) {
    LogosResult qr;
    qr.success = r.success;
    qr.value = nlohmannToQVariant(r.value);
    qr.error = r.error.empty() ? QVariant() : QVariant(QString::fromStdString(r.error));
    return qr;
}
} // anonymous namespace

class AgentProviderObject : public LogosProviderBase {
    LOGOS_PROVIDER(AgentProviderObject, "agent", "0.1.0")

public:
    LogosResult configure(const QString& ownerAddress, const QString& policyHashHex) {
        auto _result = m_impl.configure(ownerAddress.toStdString(), policyHashHex.toStdString());
        return stdResultToQt(_result);
    }

    LogosResult start() {
        auto _result = m_impl.start();
        return stdResultToQt(_result);
    }

    LogosResult stop() {
        auto _result = m_impl.stop();
        return stdResultToQt(_result);
    }

    QString skills() {
        auto _result = m_impl.skills();
        return QString::fromStdString(_result);
    }

    QString status() {
        auto _result = m_impl.status();
        return QString::fromStdString(_result);
    }

    QString invoke(const QString& name, const QString& paramsJson) {
        auto _result = m_impl.invoke(name.toStdString(), paramsJson.toStdString());
        return QString::fromStdString(_result);
    }

protected:
    void onInit(LogosAPI* api) override {
        if (!api) return;
        _logos_codegen_::maybeSetContext(m_impl,
            api->property("modulePath").toString().toStdString(),
            api->property("instanceId").toString().toStdString(),
            api->property("instancePersistencePath").toString().toStdString());
        m_logosModules = std::make_unique<LogosModules>(api);
        _logos_codegen_::maybeSetLogosModules(m_impl, m_logosModules.get());
        _logos_codegen_::maybeSetEmitEvent(m_impl,
            [this](const std::string& name, void* args) {
                emitEvent(QString::fromStdString(name),
                          *static_cast<QVariantList*>(args));
            });
    }

protected:
    void emitModulestarted(bool success, const QString& message, int timestamp) {
        emitEvent("moduleStarted", QVariantList{QVariant::fromValue(success), QVariant::fromValue(message), QVariant::fromValue(timestamp)});
    }

    void emitModulestopped(bool success, const QString& message, int timestamp) {
        emitEvent("moduleStopped", QVariantList{QVariant::fromValue(success), QVariant::fromValue(message), QVariant::fromValue(timestamp)});
    }

private:
    std::unique_ptr<LogosModules> m_logosModules;
    AgentModuleExport m_impl;
};

class AgentPlugin : public QObject, public PluginInterface, public LogosProviderPlugin {
    Q_OBJECT
    Q_PLUGIN_METADATA(IID LogosProviderPlugin_iid FILE "metadata.json")
    Q_INTERFACES(PluginInterface LogosProviderPlugin)

public:
    QString name() const override { return QStringLiteral("agent"); }
    QString version() const override { return QStringLiteral("0.1.0"); }
    LogosProviderObject* createProviderObject() override {
        return new AgentProviderObject();
    }
};
