// AUTO-GENERATED by logos-cpp-generator -- do not edit
#include "agent_qt_glue.h"
#include <QJsonArray>
#include <QJsonObject>
#include <QVariant>
#include <QString>
#include "logos_types.h"

QVariant AgentProviderObject::callMethod(const QString& methodName, const QVariantList& args)
{
    if (methodName == "configure") {
        return QVariant::fromValue(configure(args.at(0).toString(), args.at(1).toString()));
    }
    if (methodName == "start") {
        return QVariant::fromValue(start());
    }
    if (methodName == "stop") {
        return QVariant::fromValue(stop());
    }
    if (methodName == "skills") {
        return QVariant::fromValue(skills());
    }
    if (methodName == "status") {
        return QVariant::fromValue(status());
    }
    if (methodName == "invoke") {
        return QVariant::fromValue(invoke(args.at(0).toString(), args.at(1).toString()));
    }
    if (methodName == "approveSpend") {
        return QVariant::fromValue(approveSpend(args.at(0).toString(), args.at(1).toString()));
    }
    qWarning() << "AgentProviderObject::callMethod: unknown method:" << methodName;
    return QVariant();
}

QJsonArray AgentProviderObject::getMethods()
{
    QJsonArray methods;
    {
        QJsonObject obj;
        obj["name"] = QStringLiteral("configure");
        obj["returnType"] = QStringLiteral("LogosResult");
        obj["isInvokable"] = true;
        obj["signature"] = QStringLiteral("configure(QString,QString)");
        QJsonArray params;
        params.append(QJsonObject{{"type", QStringLiteral("QString")}, {"name", QStringLiteral("ownerAddress")}});
        params.append(QJsonObject{{"type", QStringLiteral("QString")}, {"name", QStringLiteral("policyHashHex")}});
        obj["parameters"] = params;
        methods.append(obj);
    }
    {
        QJsonObject obj;
        obj["name"] = QStringLiteral("start");
        obj["returnType"] = QStringLiteral("LogosResult");
        obj["isInvokable"] = true;
        obj["signature"] = QStringLiteral("start()");
        methods.append(obj);
    }
    {
        QJsonObject obj;
        obj["name"] = QStringLiteral("stop");
        obj["returnType"] = QStringLiteral("LogosResult");
        obj["isInvokable"] = true;
        obj["signature"] = QStringLiteral("stop()");
        methods.append(obj);
    }
    {
        QJsonObject obj;
        obj["name"] = QStringLiteral("skills");
        obj["returnType"] = QStringLiteral("QString");
        obj["isInvokable"] = true;
        obj["signature"] = QStringLiteral("skills()");
        methods.append(obj);
    }
    {
        QJsonObject obj;
        obj["name"] = QStringLiteral("status");
        obj["returnType"] = QStringLiteral("QString");
        obj["isInvokable"] = true;
        obj["signature"] = QStringLiteral("status()");
        methods.append(obj);
    }
    {
        QJsonObject obj;
        obj["name"] = QStringLiteral("invoke");
        obj["returnType"] = QStringLiteral("QString");
        obj["isInvokable"] = true;
        obj["signature"] = QStringLiteral("invoke(QString,QString)");
        QJsonArray params;
        params.append(QJsonObject{{"type", QStringLiteral("QString")}, {"name", QStringLiteral("name")}});
        params.append(QJsonObject{{"type", QStringLiteral("QString")}, {"name", QStringLiteral("paramsJson")}});
        obj["parameters"] = params;
        methods.append(obj);
    }
    {
        QJsonObject obj;
        obj["name"] = QStringLiteral("approveSpend");
        obj["returnType"] = QStringLiteral("LogosResult");
        obj["isInvokable"] = true;
        obj["signature"] = QStringLiteral("approveSpend(QString,QString)");
        QJsonArray params;
        params.append(QJsonObject{{"type", QStringLiteral("QString")}, {"name", QStringLiteral("requestId")}});
        params.append(QJsonObject{{"type", QStringLiteral("QString")}, {"name", QStringLiteral("verdict")}});
        obj["parameters"] = params;
        methods.append(obj);
    }
    return methods;
}
