#!/usr/bin/env python3
# SPDX-License-Identifier: MIT OR Apache-2.0
"""The test count README.md states is what that suite actually passes.

    ./scripts/check-test-count.py

WHY THIS EXISTS

README.md is a runnable walkthrough: every section is a command with its output.
One of those commands carries a count in its comment — `cargo test --workspace
--release --locked      # the policy crate, 24 tests` — and a reader runs the
line and compares. Nothing compared it for them. A suite that grows does not
fail; it runs more tests than the comment beside it admits, and CI stays green
through the whole drift.

`scripts/check-docs.py` already holds this repository to a great deal: the skill
catalogue against the registry, the job-count claims against ci.yml, the
retracted claims against every document that could restate one, and every path,
link and symbol citation. It does not count tests. This does, and only that.

The count is what `cargo test` reports passing, not the number of `#[test]`
attributes in the tree — the two stop agreeing the moment a test is `#[ignore]`d,
generated by a macro, or compiled out behind a feature. The one a reader
reproduces by running the documented command is the one cargo prints.

A SUITE THAT FAILS TO BUILD PASSES ZERO TESTS, and zero against a sentence is a
confident mismatch about entirely the wrong thing, so a non-zero cargo exit is
surfaced as itself before any comparison.
"""
import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RUNNING = re.compile(r"^\s*Running (?:unittests )?(\S+)", re.M)
RESULT = re.compile(r"^test result: ok\. (\d+) passed", re.M)

# (what the README says, which package, which suite — None for the whole package)
#
# Anchored on the words around each number, not on the number itself: a README
# that drops a claim fails here rather than passing because there is nothing
# left to compare.
CLAIMS = [
    (r"the policy crate, (\d+) tests\b", "agent-policy-core", None),
]

_ran = {}


def suites(pkg):
    """Per-suite passing counts for a package, memoised. Suites keyed by the
    binary's source file stem, which is what `Running tests/foo.rs` names."""
    if pkg not in _ran:
        r = subprocess.run(["cargo", "test", "-p", pkg, "--release"],
                           cwd=ROOT, capture_output=True, text=True)
        out = r.stdout + r.stderr
        if r.returncode != 0:
            _ran[pkg] = (None, out)
        else:
            names = [os.path.splitext(os.path.basename(m))[0].split(" ")[0]
                     for m in RUNNING.findall(out)]
            counts = [int(n) for n in RESULT.findall(out)]
            _ran[pkg] = (dict(zip(names, counts)) if names else {}, out)
    return _ran[pkg]


def main():
    with open(os.path.join(ROOT, "README.md"), encoding="utf-8") as fh:
        text = re.sub(r"\s+", " ", fh.read())

    failures = []
    checked = 0
    for pattern, pkg, suite in CLAIMS:
        found = re.findall(pattern, text)
        if not found:
            failures.append("README.md no longer states the claim matched by %r. That "
                            "sentence is what this gate defends; losing it silently is "
                            "a check going away, not a tree getting cleaner." % pattern)
            continue
        if len(set(found)) > 1:
            failures.append("the claim %r appears with different numbers (%s); a reader "
                            "cannot tell which is meant" % (pattern, ", ".join(sorted(set(found)))))
            continue
        claimed = int(found[0])
        per, out = suites(pkg)
        if per is None:
            print("`cargo test -p %s --release` did not build. A suite that does not\n"
                  "build passes zero tests, and zero against a README is a mismatch\n"
                  "about the wrong thing. The build is the failure:\n" % pkg)
            print("\n".join(out.strip().splitlines()[-12:]))
            return 1
        if suite is None:
            actual, what = sum(per.values()), "the whole %s suite" % pkg
        elif suite not in per:
            failures.append("suite %r was not run by `cargo test -p %s` — it was "
                            "renamed or removed, so the claim of %d cannot be checked "
                            "at all" % (suite, pkg, claimed))
            continue
        else:
            actual, what = per[suite], "%s/tests/%s.rs" % (pkg, suite)
        checked += 1
        mark = "ok  " if actual == claimed else "FAIL"
        print("  %s README says %-3d for %s; it passes %d" % (mark, claimed, what, actual))
        if actual != claimed:
            failures.append("README.md says %d where %s passes %d. The README is what a "
                            "reader takes for how much is checked, and it is quoted "
                            "outward, so it is the one that moves." % (claimed, what, actual))

    print("checked %d of %d stated test count(s) against the suites"
          % (checked, len(CLAIMS)))
    # The README also says the demo runs "a full 3-of-5 lifecycle" and reports a
    # compute cost. Neither is a count, and neither is checked here; they are
    # gated by the demo script's own exits.
    if failures:
        print("\n%d claim(s) the suites do not support:\n" % len(failures))
        for f in failures:
            print("  " + f)
        return 1
    print("every stated count is what its suite passes")
    return 0


if __name__ == "__main__":
    sys.exit(main())
